<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>b_AlumniCorporate(CEGACTMITSAP)</name>
   <tag></tag>
   <elementGuidId>417f9b2f-c51e-44e6-aca0-1b393061096d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>b</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='bg']/div/header/div/div/div[2]/button[2]/a/b</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Alumni/Corporate (CEG/ACT/MIT/SAP)&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>b</value>
      <webElementGuid>ef7543e3-fcc8-45e9-87ad-f65b820da29c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Alumni/Corporate(CEG/ACT/MIT/SAP)</value>
      <webElementGuid>5a159f6c-5403-44ad-924a-1f7069a0c620</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bg&quot;)/div[@class=&quot;page-wraper&quot;]/header[@class=&quot;site-header mo-left header&quot;]/div[@class=&quot;sticky-header main-bar-wraper navbar-expand-lg&quot;]/div[@class=&quot;main-bar clearfix&quot;]/div[@class=&quot;mt-3&quot;]/button[@class=&quot;btn&quot;]/a[1]/b[1]</value>
      <webElementGuid>4beb4b41-6e8c-4cce-b8f7-f1a2ebfcc04e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='bg']/div/header/div/div/div[2]/button[2]/a/b</value>
      <webElementGuid>8b104359-05b3-4d62-99ec-52c79ac230dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact Us'])[1]/following::b[1]</value>
      <webElementGuid>59f42600-51be-4057-9ddc-c17e6bb784b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RCC'])[1]/following::b[1]</value>
      <webElementGuid>f84dcb62-8d1e-4df2-9249-6be20721e621</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sustainability'])[1]/preceding::b[1]</value>
      <webElementGuid>bce29bb9-acf6-4981-8904-2607e59abf35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CEAP 2024(M.E./M.Tech./M.Arch./M.Plan.)'])[1]/preceding::b[2]</value>
      <webElementGuid>acc60800-4519-4ff3-8c79-cecb82c3a317</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Alumni/Corporate']/parent::*</value>
      <webElementGuid>e7fdd70a-85b9-4312-9e2f-20e574a10eea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//b</value>
      <webElementGuid>2e5d051c-b919-4847-87c6-f0a8ad356374</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//b[(text() = 'Alumni/Corporate(CEG/ACT/MIT/SAP)' or . = 'Alumni/Corporate(CEG/ACT/MIT/SAP)')]</value>
      <webElementGuid>3807eb78-cc74-4f81-a1a1-56d48a85e6e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
