<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_NIRF</name>
   <tag></tag>
   <elementGuidId>c7f2e260-b6c9-49fb-8c3e-36c99a88ef1c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.level0.parent.drop-menu.active > a > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='nav']/li[12]/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#nav >> internal:role=link[name=&quot;NIRF&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>65c531eb-e49f-43fb-ac49-99b2897e001f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NIRF</value>
      <webElementGuid>4aaaeb72-47ef-47dc-9267-f81a09a36bb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav&quot;)/li[@class=&quot;level0 parent drop-menu active&quot;]/a[1]/span[1]</value>
      <webElementGuid>a39ff97d-d1e6-428b-8dd0-3b7eccef1ab6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='nav']/li[12]/a/span</value>
      <webElementGuid>5bca7765-fc5a-4377-9199-abd8b766d867</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NAAC'])[2]/following::span[1]</value>
      <webElementGuid>c9aa0007-ef24-4ab0-a852-4871fc9caf49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IQAC'])[2]/following::span[2]</value>
      <webElementGuid>f54aeffb-e996-4258-bd52-10d0fb87f55f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CONTACT'])[2]/preceding::span[1]</value>
      <webElementGuid>b0cb6482-06de-498a-a302-63c3456ea555</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NIRF 2023'])[1]/preceding::span[2]</value>
      <webElementGuid>aea9e986-36da-4dfc-bc9f-53eef07ef22a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li[12]/a/span</value>
      <webElementGuid>567b0f5b-7418-4975-8463-b12c6c8cfc60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'NIRF' or . = 'NIRF')]</value>
      <webElementGuid>ff992ea5-afc8-4976-9426-1b3aa26a4ca7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
