<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Services</name>
   <tag></tag>
   <elementGuidId>1c6ca2bd-4077-4bbf-90e7-340da4b673b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#avia-menu > #menu-item-48 > a > span.avia-menu-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//li[@id='menu-item-48']/a/span[2])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Services&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>aa1011a1-bc5a-4eee-aae4-3de58bf35492</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>avia-menu-text</value>
      <webElementGuid>2be71846-247b-4e4d-90b4-64401dd1444c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Services</value>
      <webElementGuid>5b2dbf56-a15f-4168-b57f-5959c35f3382</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;avia-menu&quot;)/li[@id=&quot;menu-item-48&quot;]/a[1]/span[@class=&quot;avia-menu-text&quot;]</value>
      <webElementGuid>626e6c09-769b-4c1a-a710-1663c1bfa07d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//li[@id='menu-item-48']/a/span[2])[2]</value>
      <webElementGuid>c156be13-4550-4389-a44a-6c97fd69d5fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[2]/following::span[5]</value>
      <webElementGuid>db69a148-9eef-4872-8891-1400a502c061</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Youtube'])[1]/following::span[7]</value>
      <webElementGuid>183897b9-fab6-42b7-a1fb-ad0faacc5746</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Consultancy-Service'])[2]/preceding::span[6]</value>
      <webElementGuid>c0a585fe-b5e4-4b0f-864a-be1eca068931</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cisco Training Service'])[2]/preceding::span[8]</value>
      <webElementGuid>278b65ab-6335-4de3-b498-147ff8a5990a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/div/ul/li[2]/a/span[2]</value>
      <webElementGuid>176baf6e-d8df-4d3a-83c8-d05721253169</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Services' or . = 'Services')]</value>
      <webElementGuid>49c8c4cc-16b4-46cd-980d-fb40dd9dcf48</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
