<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_E-Resources</name>
   <tag></tag>
   <elementGuidId>a529ec55-1cc9-4f66-9be6-04101f617f7d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nav > li.level1.nav-1-5.parent > a > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='nav']/li[7]/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;E-Resources&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7699b11d-bcde-424b-b814-c52a11bc6a0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>E-Resources</value>
      <webElementGuid>e04ef5ef-dc1e-4f72-99db-cea6bf3e3bcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav&quot;)/li[@class=&quot;level1 nav-1-5 parent&quot;]/a[1]/span[1]</value>
      <webElementGuid>99802b48-c268-4449-9970-a5d28ab3ad0d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='nav']/li[7]/a/span</value>
      <webElementGuid>3e01284f-4a74-47e2-8e4b-f1f544a68a0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='STUDENT SUPPORT'])[2]/following::span[1]</value>
      <webElementGuid>379dac19-5e1e-4a4f-9e49-122e9f53322d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DEPARTMENTS'])[2]/following::span[2]</value>
      <webElementGuid>d2d7effa-da9b-4597-8805-a2488c236a43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GALLERY'])[1]/preceding::span[1]</value>
      <webElementGuid>2e64e614-f087-4e3c-b9e8-3d8196402a0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ALUMNI'])[2]/preceding::span[2]</value>
      <webElementGuid>3519c719-daaa-4fa3-9f50-14dbf7c332bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li[7]/a/span</value>
      <webElementGuid>7c1266b3-0b66-4d4e-b303-5d361331855d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'E-Resources' or . = 'E-Resources')]</value>
      <webElementGuid>2dc17fe4-6c18-4c45-acda-0a52fb369af9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
